### ISSUE TITLE
'Undefined is not an object' Error when rendering DropIn component

### ISSUE THREAD

**Issue by rbsmidt** [jeffcarp/braintree-react#10]
Hi there.
I'm trying to test braintree-react in a project, but i keep getting an error when trying to render the DropIn-component:

    undefined is not an object (evaluating 'deepestAncestor.firstChild')

I'm bundling my project with WebPack, and installed braintree react via NPM. I then pretty much followed the code from the repo's example:

    // BrainTree x React
    var DropIn = require('braintree-react').DropIn;
    var braintree = require('braintree-web');

And then when i want to render the Drop-in:

    <div className="dropin-wrapper">
        <DropIn braintree={braintree} clientToken={this.props.token} rootClassName="dropin-wrapper" />
    </div>

... Where this.props.token is a token returned from my backend and generated with Braintree API.
If i examine the stacktrace through the browser console, the error leads me to this line in my main.js bundled by WebPack:

    } finally {
        this._isInTransaction = false;
    }

Iam using React with addons and React Router in my application as well. Any idea, what could cause this error?

Full stack trace from the browser looks like this:
    [Error] TypeError: undefined is not an object (evaluating 'deepestAncestor.firstChild')
	perform (main.js, line 5406)
	batchedUpdates (main.js, line 16519)
	enqueueUpdate (main.js, line 4021)
	enqueueUpdate (main.js, line 3440)
	enqueueSetState (main.js, line 3618)
	setState (main.js, line 3322)
	(anonymous function) (main.js, line 197)
	(anonymous function) ([native code], line 0)
	fire (jquery-1.11.3.js, line 3148)
	fireWith (jquery-1.11.3.js, line 3260)
	done (jquery-1.11.3.js, line 9314)
	callback (jquery-1.11.3.js, line 9718)

**Comment by rbsmidt** [comment]
Ok i've been diggin a little further into this. If i log my DropIn var in console i get this message:

    // This constructor is overridden by mocks. The argument is used
      // by mocks to assert on what gets mounted.

Followed by a lot of React explanation and functions - but clearly no DropIn component. Googling around it seems, that this issue appears, when more than one instance of React is loaded, and starts conflicting with each other.
I'm using v. 0.13 with add-ons. 

Is there a bundled version of React inside the react-braintree npm package?

Any pointers to how i get around this issue?

**Comment by jeffcarp** [comment]
Hey @rbsmidt, braintree-react used to bundle all of React but it no longer does. My only idea is that the dual-loading could have something to do with this line: https://github.com/jeffcarp/braintree-react/blob/master/lib/dropin.js#L6

Can you try removing `global.React` so the function looks like:

```js
function getReact() {
  return require('react');
}
```

And see if that improves things?

**Comment by rbsmidt** [comment]
Hey @jeffcarp 

Removing the global.React from dropin.js did indeed worked! Thanks a lot for your quick and useful reply :+1: 
I'll close the issue. Thanks again.


Best regards

**Comment by jeffcarp** [comment]
Hey @rbsmidt, glad that worked! I'm going to go ahead and remove the `getReact` function from this module since it seems like unexpected functionality for a React component. Thanks for bringing this up! :smile_cat:
