### ISSUE TITLE
Improve error handling

### ISSUE THREAD

**Issue by ir-fuel** [jeffcarp/braintree-react#19]
I don't know why it happens, but this is the scenario:

I integrated this component and created a sandbox account + keys.

Tried doing a payment by typing a credit card number and I got the "There was an error processing your request" overlay on the component. I have the `onError` callback implemented but nothing showed up there.
Wondering what was going on I checked the network requests in Chrome debugger and there I found this response in one of the calls being made:
```
/**/callback_json29a79f6ae41146f5893b5ffb3350a389({"error":{"message":"Credit card is invalid"},"fieldErrors":[{"field":"creditCard","fieldErrors":[{"field":"number","code":"81717","message":"Credit card number is not an accepted test number"}]}],"status":422})
```

Apparently I needed to register a credit card number for testing.

Maybe you know why this error never got to my `onError` function?

Thanks

**Comment by jeffcarp** [comment]
Hey @ir-fuel, does the same thing happen if you use one of the numbers on this page? https://developers.braintreepayments.com/reference/general/testing/#no-credit-card-errors

**Comment by ir-fuel** [comment]
You can reproduce it with `3566002020360505`

**Comment by jeffcarp** [comment]
What about one of the numbers from the BT docs?

**Comment by ir-fuel** [comment]
That is a number from the BT docs

**Comment by kyledetella** [comment]
@ir-fuel are you using Drop-in?

**Comment by ir-fuel** [comment]
That's exactly it.
Seems you can't really fix it.
