### ISSUE TITLE
Improve 'Change Payment Method'

### ISSUE THREAD

**Issue by ir-fuel** [jeffcarp/braintree-react#20]
I don't know if it is technically possible, but right now I am using this component inside a Bootstrap modal. It all works fine, however if I click on "Change Payment Method" there is this popup appearing that whites out my entire screen. Wouldn't it make more sense to have it overlap the parent form and not the entire screen, or is this something internal to the Braintree component?

**Comment by jeffcarp** [comment]
Hi @ir-fuel, sorry this is so late. It looks like Bootstrap doesn't support multiple modals without a custom workaround: http://getbootstrap.com/javascript/#modals

**Comment by jeffcarp** [comment]
@ir-fuel it sounds like this issue is related to https://github.com/braintree/braintree-web/issues/142

**Comment by jeffcarp** [comment]
Closing, please feel free to re-open if this is still an issue.
