### ISSUE TITLE
Webpack warning on build

### ISSUE THREAD

**Issue by jforaker** [jeffcarp/braintree-react#21]
Get this error with webpack, when replicating examples:

```
WARNING in ./~/braintree-web/dist/braintree.js
Critical dependencies:
3:420-427 This seems to be a pre-built javascript file. Though this is possible, it's not recommended. Try to require the original source to get better results.
 @ ./~/braintree-web/dist/braintree.js 3:420-427
```

**Comment by jeffcarp** [comment]
`braintree-web` is only distributed in minified form (see https://github.com/braintree/braintree-web/issues/1), so I don't think there's any way to mitigate that warning right now.

**Comment by kyledetella** [comment]
@jeffcarp is right. There are a few issues on the braintree-web repo around this matter. This [particular thread](https://github.com/braintree/braintree-web/issues/52#issuecomment-119237298) may help shed more light.

**Comment by christensena** [comment]
I'm using the `noParse` option in the `module` section in my web pack config to stop it even looking at the  braintree.js file. A workaround but does the trick.

**Comment by jeffcarp** [comment]
Closing, please re-open if you have any questions
