### ISSUE TITLE
CVV checking

### ISSUE THREAD

**Issue by KristerV** [jeffcarp/braintree-react#31]
hey, is there no CVV checking? Seems incredibly basic.

**Comment by kyledetella** [comment]
@KristerV can you elaborate?

**Comment by KristerV** [comment]
Well when entering credit card details theres the card number and
expiration date, but no security code check. The one ok the back of the
card.

**Comment by kyledetella** [comment]
As with #32 this is a Braintree issue, not really to do with this library, but have you probably need to enable CVV verification for your merchant account and then the field will render: https://articles.braintreepayments.com/guides/fraud-tools/avs-cvv#enabling-avs-and-cvv-rules

> If you use our Drop-in UI and you enable CVV rules or AVS rules for postal codes in the Control Panel, the fields needed to collect that information will automatically appear on your checkout form.

**Comment by KristerV** [comment]
well I've got it enabled, but it aint showing up. I had assumed this react framework didn't make it happen, am I wrong?
![screenshot_2016-08-10_18-01-36](https://cloud.githubusercontent.com/assets/2750622/17558870/c429bf8c-5f24-11e6-92b1-ccab397d4bf2.png)

**Comment by kyledetella** [comment]
That's interesting, if you setup your Drop-in outside of `braintree-react` does the CVV field show up?

I can't think of a way that this library would (or even could) interfere with the CVV field rendering. In Drop-in, that decision is made server-side by Braintree. I would reach out to Braintree support or file an issue on their [JS repo](https://github.com/braintree/braintree-web/issues), they will be able to better diagnose your issue.

**Comment by KristerV** [comment]
hmm, no, CVV is not showing up even with the official form.

**Comment by KristerV** [comment]
ah this fucking thing is so much more complicated than what I expected..
